#!/usr/bin/env python3
"""Convert a little-endian RV32I text binary into a $readmemh word image."""

from __future__ import annotations

import argparse
import pathlib
import struct
import sys


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert a raw RV32I text binary into a .mem image")
    parser.add_argument("src", help="input binary file")
    parser.add_argument("dst", help="output .mem file")
    args = parser.parse_args()

    src_path = pathlib.Path(args.src)
    dst_path = pathlib.Path(args.dst)

    raw = src_path.read_bytes()
    if len(raw) % 4:
        raw += b"\x13\x00\x00\x00"[: 4 - (len(raw) % 4)]

    lines: list[str] = [
        "// ============================================================================",
        "// Auto-generated by tools/elf_text_to_mem.py",
        "// ============================================================================",
        "",
    ]

    for word_idx in range(0, len(raw), 4):
        word = struct.unpack_from("<I", raw, word_idx)[0]
        lines.append(f"{word:08x} // PC={word_idx:04x}")

    lines.append("")
    dst_path.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
